Realiza modelagem de cardapio no MongoDB
SoLanches/API-SoLanches pull request #21
Opened 2021-07-22 01:53 UTC by dnlgomesl

Modelei o cardápio com o mesmo id de comércio, por simplificação e não consegui ver problemas nisso, porém ainda em aberto.

2021-07-22 21:49 UTC, claudiodantas requested changes
Show! Deixei algumas sugestões. Acho que só o que faltou foram os métodos não estáticos para adicionar produto e adicionar destaques, e seus respectivos gets

2021-07-22 21:49 UTC, claudiodantas commented on solanches/models.py
> +    def __init__(self, comercio_id, produtos, destaques):
É bom colocar como valor padrão listas vazias em produtos e destaques, para não serem obrigatórios
```suggestion
    def __init__(self, comercio_id, produtos=[], destaques=[]):
```

2021-07-22 21:49 UTC, claudiodantas commented on solanches/models.py
> +        self.comercio_id = comercio_id
```suggestion
        self._id = comercio_id
```

2021-07-22 21:49 UTC, claudiodantas commented on solanches/models.py
> +        self._id = self.comercio_id
```suggestion
```

2021-07-23 13:50 UTC, dnlgomesl commented on solanches/models.py
> +    def __init__(self, comercio_id, produtos, destaques):
Feito!

2021-07-23 13:51 UTC, dnlgomesl commented on solanches/models.py
> +        self.comercio_id = comercio_id
Ok

2021-07-23 13:51 UTC, dnlgomesl commented on solanches/models.py
> +        self._id = self.comercio_id
Ok

2021-07-25 13:07 UTC, dnlgomesl commented
Show!

2021-07-26 16:26 UTC, merged