Armazenando os dados não sensíveis das entidades em um campo self.attributes e utilizando o update_one para o método de save
SoLanches/API-SoLanches pull request #28
Opened 2021-07-28 23:19 UTC by dnlgomesl

2021-08-01 23:30 UTC, claudiodantas requested changes
Muito bom, Daniel!!! Só a parte do Handler que eu tenho algumas considerações. Colocar o status code no `abort` me parece que limita a solução. Não temos como garantir, por exemplo, que se ocorrer alguma exceção em determinada função do controller, ela provocará um código 400 ou 404. Pode ser um 500, pode ser um 403, etc. Por isso acho bacana a gente trabalhar com o lançamento de Errors e Exceptions, ao invés dos códigos. O que achas?


PS: Cuidado para das próximas vezes deixar uma branch para cada task, para podermos trabalhar de forma separada a evolução de cada uma.

2021-08-01 23:30 UTC, claudiodantas commented on solanches/controller.py
> +    assert attributes and type(attributes) is dict, "Erro: atriutos inválidos!"
```suggestion
    assert attributes and type(attributes) is dict, "Erro: atributos inválidos!"
```

2021-08-01 23:30 UTC, claudiodantas commented on solanches/controller.py
> +    assert attributes and type(attributes) is dict, "Erro: atriutos inválidos!"
```suggestion
    assert attributes and type(attributes) is dict, "Erro: atributos inválidos!"
```

2021-08-01 23:30 UTC, claudiodantas commented on solanches/rest.py
> +        abort(400)
Não tenho como garantir que a exception lançada no cadastra_comercio foi culpa do usuário. Pode ter vindo por erro de implementação ou do bd, por exemplo. Dessa forma, apontar um status 400 estaria semanticamente errado

2021-08-02 11:37 UTC, dnlgomesl commented
> Muito bom, Daniel!!! Só a parte do Handler que eu tenho algumas considerações. Colocar o status code no `abort` me parece que limita a solução. Não temos como garantir, por exemplo, que se ocorrer alguma exceção em determinada função do controller, ela provocará um código 400 ou 404. Pode ser um 500, pode ser um 403, etc. Por isso acho bacana a gente trabalhar com o lançamento de Errors e Exceptions, ao invés dos códigos. O que achas?
> 
> PS: Cuidado para das próximas vezes deixar uma branch para cada task, para podermos trabalhar de forma separada a evolução de cada uma.

Okok! Fiquei na dúvida sobre branchs,  como as tasks eram mais curtas.

2021-08-03 15:19 UTC, claudiodantas commented
Eu optei por tornar opcional o campo attributes de Produto por não ter nenhum atributo obrigatório (isso pode mudar no futuro). Eu vou aprovar esse PR pra fazer logo o merge com a master e o pessoal conseguir adaptar os outros PRs, mas a task do handler vou colocar como em andamento porque ela ainda não foi concluída.

2021-08-03 15:19 UTC, claudiodantas approved these changes

2021-08-03 15:19 UTC, merged