Adiciona edição de um produto de comércio
SoLanches/API-SoLanches pull request #41
Opened 2021-08-13 05:18 UTC by dnlgomesl

2021-08-18 01:26 UTC, claudiodantas requested changes
Algumas sugestões

2021-08-18 01:26 UTC, claudiodantas commented on solanches/controller.py
> +    produto = Produto.get_by_id(produto_id)
A ideia é que o controller só tenha acesso aos produtos por meio da interface de `Comercio`, sem recorrer à `Produto` ou `Cardapio`. Então tu pode criar um método em `Comercio` que vai verificar se o produto está cadastrado nele, através da comunicação hierárquica que a gente definiu:

```
Comercio -> Cardapio -> Produto
```

2021-08-18 01:26 UTC, claudiodantas commented on solanches/rest.py
> +    attributes = req.get("attributes") if "attributes" in req else {}
É bom se certificar de que o attributes passado é um dict. Como python não é tipada, eu testei o cadastro com uma string e ele funcionou, mudando o tipo de attributes de produto

2021-08-18 12:08 UTC, dnlgomesl commented on solanches/rest.py
> +    attributes = req.get("attributes") if "attributes" in req else {}
ok

2021-08-18 12:09 UTC, dnlgomesl commented on solanches/controller.py
> +    produto = Produto.get_by_id(produto_id)
ok

2021-08-22 23:41 UTC, claudiodantas approved these changes

2021-08-22 23:41 UTC, claudiodantas commented on solanches/controller.py
> +    produto = Produto.get_by_id(produto_id)
Eu ia pedir pra tu mudar isso aqui pra continuar com a ideia de o controller "conversar" apenas com o `Comercio` ao invés de `Produto`, mas estou começando a repensar essa ideia kkkk Porque em casos como esse realmente acredito que não faça tanta diferença já que já foi verificado que o produto está no comércio...

2021-08-23 00:02 UTC, dnlgomesl commented on solanches/controller.py
> +    produto = Produto.get_by_id(produto_id)
Concordo

2021-08-23 19:54 UTC, merged