testes remove comercio
SoLanches/API-SoLanches pull request #56
Opened 2021-08-29 01:50 UTC by EduardoNunes5

2021-09-01 23:23 UTC, emys-alb approved these changes

2021-09-11 18:36 UTC, claudiodantas requested changes
#TODO: nome inválido

2021-09-11 18:36 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +@mock.patch('solanches.models.Comercio')
Aqui deve ser mockada a função Comercio.get_by_name. Imagino que o retorno dela não seja uma exception, mas sim algo como uma lista vazia ou um dict vazio. Não tenho certeza. Se for uma exception, verifica qual é (do pymongo.erros) e substitui no tratamento do pytest.raises

2021-09-11 18:36 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +@mock.patch('solanches.models.Cardapio.get_by_id')
não precisa do mock dessa função

2021-09-13 02:24 UTC, EduardoNunes5 commented
adicionei o mongomock no requirements.txt

2021-09-13 22:27 UTC, claudiodantas commented
> adicionei o mongomock no requirements.txt, quando rodei os testes estava faltando ele

O mongomock não deve ficar no requirements.txt mesmo não, mas sim no tests-requirements.txt

2021-09-13 23:13 UTC, merged