Teste da feature cadastrar comercio
SoLanches/API-SoLanches pull request #58
Opened 2021-08-29 20:50 UTC by anacarolinacv

2021-09-02 00:59 UTC, emys-alb requested changes

2021-09-02 00:59 UTC, emys-alb commented on solanches/tests/test_rest.py
> +    response = client.post(url)
Para as funções de cadastro no rest é esperado que o cadastro seja feito pelo post com `client.post(url, data=jsonComercio)` ao invés de mockado pelo controller

2021-09-02 00:59 UTC, emys-alb commented on solanches/tests/test_controller.py
> +    assert comercio_nome == result[comercio_nome]
comercio_nome não é chave de comercio é apenas 'nome'

2021-09-28 17:43 UTC, claudiodantas requested changes
Aparentemente os casos de testes estão sendo cobertos. Só pedi algumas mudanças e a conclusão de alguns testes

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +import pytest
O import do pytest já estava no local correto, como indicado pelo PEP8.

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +from pymongo.errors import DuplicateKeyError
Esse import deve ficar no mesmo "grupo" do import do pytest, por serem de bibliotecas externas.

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +@pytest.mark.skip(reason="TODO")
Não faz mais sentido ter o skip, o teste já pode ser feito normalmente

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +def test_cadastra_comercio(mock_get_by_name, mock_get_by_id, controller):
A ordem dos parâmetros dos mocks está ao contrário. A ordem deve ser de baixo pra cima, ou seja:
```suggestion
def test_cadastra_comercio(mock_get_by_id, mock_get_by_name, controller):
```

Além disso, não faz sentido mockar método algum da classe Cardapio pois ela não é chamada em nenhum momento na função.

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +    comercio_nome = 90992727
No caso não é `..._sem_nome`, mas sim `..._com_nome_invalido`

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +    password = 0
Mais uma vez, não é `..._sem_senha`, mas sim `..._com_senha_invalida`. Sugiro que você mude também a mensagem do controller de `"Erro: Senha não informada!"` para `"Erro: campo senha inválido!"`

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +    comercio_attributes = 48488448
Para deixar o teste mais legível
```suggestion
    attributes_nao_eh_dict = 48488448
```

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +def test_cadastra_comercio_sem_horarios(controller):
```suggestion
def test_cadastra_comercio_attributes_sem_horarios(controller):
```

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +def test_cadastra_comercio_sem_endereco(controller):
```suggestion
def test_cadastra_comercio_attributes_sem_endereco(controller):
```

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +    assert str(exinfo.value.message) == 'Erro: campo horarios não informados!'
Corrige a mensagem no controller também, por favor.
```suggestion
    assert str(exinfo.value.message) == 'Erro: campo horarios não informado!'
```

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_controller.py
> +
Também já pode ser feito. Lembrando que você vai usar o `DuplicateKeyError` do mongo pra disparar a exception no método `.save()`, mas a exception de fato que você vai verificar se foi lançada é a `SolanchesBadRequestError`, por causa do nosso `_assert`

2021-09-28 17:43 UTC, claudiodantas commented on solanches/tests/test_rest.py
> +import pytest
Mais uma vez tirasse o import do pytest do local correto

2021-09-30 11:52 UTC, merged