Substitui a rota de buscar o produto por id
SoLanches/API-SoLanches pull request #73
Opened 2021-09-08 01:40 UTC by erickems

2021-09-11 03:42 UTC, dnlgomesl requested changes
Só uma pequena mudança :)

2021-09-11 03:42 UTC, dnlgomesl commented on solanches/controller.py
>      produto = Produto.get_by_id(produto_id)
Acredito que a ideia seria o controller se comunicar com Comercio, dai o comércio faria o get de produto, algo do tipo Comercio.get_produto(produto_id, comercio_nome).

2021-09-11 20:47 UTC, erickems commented on solanches/controller.py
>      produto = Produto.get_by_id(produto_id)
Eu entendi. Nessa implementação eu quis evitar que três entidades se conversassem, por isso que eu fiz rest -> controller | controller -> comercio | controller -> produto.

2021-09-11 21:53 UTC, dnlgomesl commented on solanches/controller.py
>      produto = Produto.get_by_id(produto_id)
Na task de Gustavo ele implementa o Comercio.get_produto(comercio_nome, produto_id), então se quiser esperar o merge da certo ;)

2021-09-12 13:35 UTC, erickems commented on solanches/controller.py
>      produto = Produto.get_by_id(produto_id)
Vou ajustar. Vlw

2021-09-13 13:49 UTC, dnlgomesl approved these changes

2021-09-13 21:37 UTC, merged